PREP(pidCreate);
PREP(pidReset);
PREP(pidRun);
PREP(findModelSpaceCoordinates);
PREP(addModelSpacePoint);
PREP(reloadTurret);
PREP(toggleRenderTargets);
PREP(deployCountermeasures);
PREP(zoomTurret);
