name: hemtt

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v4
    - name: Setup HEMTT
      uses: arma-actions/hemtt@v1
    - name: Run HEMTT build
      run: hemtt build
    - name: Rename build folder
      run: mv .hemttout/build .hemttout/@hct
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: hct-${{ github.sha }}-nobin
        path: .hemttout/@*
        include-hidden-files: true # Because .hemttout is a hidden directory
        if-no-files-found: error
